# Generated by Django 5.0.2 on 2026-03-12 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto solicitado del préstamo', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_solicitud', models.DateField(help_text='Fecha en que se solicita el préstamo')),
                ('empleado', models.ForeignKey(help_text='Empleado que solicita el préstamo', on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
