# Generated by Django 5.0.2 on 2026-03-17 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_nombre_alter_historialpuesto_empleado'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('ACTIVO', 'Activo'), ('CONCLUIDO', 'Concluido'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, help_text='Fecha de aprobación del préstamo', null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_fin_descuento',
            field=models.DateField(blank=True, help_text='Fecha de fin de los descuentos en nómina', null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio_descuento',
            field=models.DateField(blank=True, help_text='Fecha de inicio de los descuentos en nómina', null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='pago_fijo_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pago fijo de capital mensual', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='plazo_meses',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='saldo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo pendiente del préstamo', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tasa_interes_mensual',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Tasa de interés mensual en porcentaje', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, help_text='Fecha de solicitud del préstamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_abono', models.PositiveIntegerField(default=1, help_text='Número secuencial del abono')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha del abono')),
                ('monto_capital', models.DecimalField(decimal_places=2, default=0, help_text='Monto del abono aplicado a capital', max_digits=12)),
                ('monto_interes', models.DecimalField(decimal_places=2, default=0, help_text='Monto del abono aplicado a intereses', max_digits=12)),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=0, help_text='Monto total cobrado en este abono', max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Saldo restante del préstamo después de este abono', max_digits=12)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='prestamos.prestamo')),
            ],
        ),
    ]
